added round arrow button design
front-end-by-rimantas/20-grupe-portfolio-mitech pull request #10
Opened 2020-12-29 15:47 UTC by Lukasring

round arrow button design and hover animation

2020-12-29 17:53 UTC, Roberta2020 commented on css/components/button.css
> +@keyframes pulse {
```suggestion
@keyframes pulse {
box-shadow: 50px var(--main-color);
```

2020-12-29 17:56 UTC, Roberta2020 submitted a review, later dismissed
Puikus darbas! 👍 
Gal tik reikėtų dar box-shadow pridėti, kad gautųsi tas pulsuojantis apskritimas. Nežinau tiksliai ar mano rekomendacija gera. :D

2020-12-29 18:14 UTC, Lukasring commented on css/components/button.css
> +@keyframes pulse {
Pasiulymas geras :) dabartiniu sprendimu pulsavimas kaip ir veikia, tik jis nera tobulas, gali tekti koreguot. Bandziau ir su box-shadow bet efektas gavosi ne visai toks kokio reikia, nors buvo arti 😄

2020-12-30 08:23 UTC, belauzas requested changes
Pamąstymai:
- jei `.btn` panaudojamas ant `<a>`, tai išlieka underline;
- jei `.btn` panaudojamas ant `<button>`, tai išlieka border;
- jei `.btn-round` panauddojamas ant `<a>`, tai sugriūna dydis, nepriklausomai nuo turinio tame elemente.

2020-12-30 11:12 UTC, belauzas approved these changes
Dar neišbandžiau, bet man regis `.btn-round:hover::after` užtektu ir `z-index: 1;`. Bet šiaip all good 👍

2020-12-30 13:31 UTC, tomasvilimas approved these changes

2020-12-30 13:57 UTC, Roberta2020 approved these changes

2020-12-30 13:57 UTC, merged