Blogs & news sector( semi-final)
front-end-by-rimantas/20-grupe-portfolio-mitech pull request #29
Opened 2020-12-30 18:40 UTC by tomasvilimas

still to do:

Link's animations
read more animations
calendar icon

2020-12-30 20:02 UTC, Lukasring requested changes
Šiaip viskas labai gerai atrodo, beliko šiek tiek pašlifuoti. Keletas bendrinių pastebėjimų, kad reiktų išnaudoti daugiau html elementų struktūrai. pvz `<ul> ir <li> <h2> <h3>` ir t.t. Šiek tiek paformatuot patį kodą, prie daug klasių palikta tiesiog kelios tuščios eilutės jose. Taip pat `font-weight` paziuret, paplonint jį jei duoda turimo šrifto galimybės. 👍
p.s kadangi pats norėjai kad pareviewinciau tai prirašiau daug 😄

2020-12-30 20:02 UTC, Lukasring commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
Kam šitas reikalingas?

2020-12-30 20:02 UTC, Lukasring commented on css/components/blogs-and-news.css
> +.list{
Dabar su tuo dar viskas gerai, bet toki bendriniai klasiu pavadinimai gali konfliktuoti ateityje su kitais, galbut reiktu konkretizuoti pvz `.updated .list`

2020-12-30 20:02 UTC, Lukasring commented on css/components/blogs-and-news.css
> +    line-height: 45px;
Manau per didelis `line-height`. Dabar kai persikelia tekstas į kitą eilutę atrodo kaip atskiras punktas. Siulyčiau nuimti `line-height` ir kiekvienam sąrašo elementui uždėti `margin-bottom`

2020-12-30 20:02 UTC, Lukasring commented on css/components/blogs-and-news.css
> +    z-index:999;
Manau ` position:relative;` ir `display:block;` geriau būtų perkelti ant pačios `.blog-photos` klasės. Turėtų veikti taip pat. `z-index` atrodo labai diziulis,  Manau jis čia nėra reikalingas, nes dabar jokios įtakos nedaro.

2020-12-30 20:02 UTC, Lukasring commented on css/components/blogs-and-news.css
> +.blog-photos {
Tokia maža pastabėlė, pakeisti klasės pavadinimą į vienaskaitą `.blog-photo` nes taikoma vienai nuotraukai 😀

2020-12-30 20:02 UTC, Lukasring commented on css/components/blogs-and-news.css
> +.ways{
Labai neaiškus klasės pavadinimas

2020-12-30 20:02 UTC, Lukasring commented on index.html
> +            <a href="#" class="list">Blockchain Technology Effects on Logistics Sector?</a>
Darant kažkokį sąrašą, struktūriškai aiškiau būtų naudoti tam skirtus elementus. 

```css
<ul class='.list'>
   <li class='.list-item'><a href='#'>Some list text</li>
</ul>
```

Taip pat matau ant *parent* `<div>` tokia pati *class* kaip ir jo *children*. Norėdamas stilizuoti *child* elementa gali naudoti sekeltorius pvz 
```css
 .class > p {/*some awesome styles */}
```

2020-12-30 20:02 UTC, Lukasring commented on index.html
> +          <img class="blog-photos" src="./images/phone.jpg" alt="">
img tagas turi uzsidaryt />

2020-12-30 20:02 UTC, Lukasring commented on index.html
> +          <p class="playrole">They play a role in making operations more seamless, bridging the gap between authorities, consumers and businesses. …</p>
Galima panaudoti daugiau html elementų, pvz h1 h2..h6. Aiškesnė struktūra tada atrodo nei kai visi p. Taip pat klasių pavadinimai galėtų būti geresni. Labiau kas yra tas elementas, ne koks jo turinys. pvz `.title` `.text` . Ir kodėl 114 ir 115 tas pats sakinys išskaidytas į kelis p elementus?

2020-12-30 20:02 UTC, Lukasring commented on index.html
> +          <p class="playrole">It is far wiser to do your own installations and ensure that all data flowing through the organization has end-to-end encryption. …</p>
Klasių pavadinimai ne į temą.

2020-12-31 15:35 UTC, Lukasring approved these changes, later dismissed
👌

2021-01-04 11:09 UTC, Lukasring approved these changes, later dismissed

2021-01-04 11:34 UTC, sunshinepro approved these changes, later dismissed

2021-01-04 11:54 UTC, JonasDudonis approved these changes, later dismissed

2021-01-04 16:20 UTC, Lukasring submitted a review, later dismissed
👍

2021-01-05 08:34 UTC, sunshinepro approved these changes, later dismissed

2021-01-05 11:34 UTC, JonasDudonis submitted a review, later dismissed

2021-01-05 11:46 UTC, Roberta2020 submitted a review, later dismissed

2021-01-05 11:47 UTC, Lukasring approved these changes

2021-01-05 11:55 UTC, Lukasring submitted a review, later dismissed

2021-01-05 12:05 UTC, Lukasring approved these changes

2021-01-05 12:05 UTC, JonasDudonis approved these changes

2021-01-05 12:06 UTC, Roberta2020 approved these changes

2021-01-05 12:06 UTC, Edvardas1989 approved these changes

2021-01-05 12:06 UTC, merged