logo banner no responsive
front-end-by-rimantas/20-grupe-portfolio-mitech pull request #62
Opened 2021-01-10 13:24 UTC by sunshinepro

ką galėjau padariau su css'u.

animacijas ir responsiv'ą darysiu kitu etapu su JS

2021-01-10 15:22 UTC, Lukasring requested changes, later dismissed
Pull requestas gerokai atsilieka nuo dabartinio develop. Reikia atnaujint

2021-01-10 15:22 UTC, Lukasring commented on css/components/logo-banner.css
> +    grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr;
`grid-template-columns: repeat(6, 1fr)` būtų trumpesnis užrašymas

2021-01-10 15:22 UTC, Lukasring commented on css/components/logo-banner.css
> +    margin-right: 30px;
Kadangi naudoji grid, tarpus gali padaryti su `gap` ant parent elemento.
Taip pat dėl grid galima lengvai išcentruoti elementus su `justify-contnet` ir `align-items` nereikės `margin`.

2021-01-13 07:56 UTC, sunshinepro commented on css/components/logo-banner.css
> +    grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr;
taip, butu. bet veikia ir toks uzrasymas :)

2021-01-13 07:58 UTC, sunshinepro commented on css/components/logo-banner.css
> +    margin-right: 30px;
Lukai, Rimantas ne karta paaiskino, kad ta pati dalyka galima suprogramuoti daugeliu budu. Kadangi mes neturejom nustate bendru taisykliu (pvz jei naudoji grida, turi naudoti gapa, o ne margin), nesuprantu kodel prasai manes tai pakeisti

2021-01-13 08:02 UTC, Lukasring commented on css/components/logo-banner.css
> +    margin-right: 30px;
Čia komentaruose tik pasiūlymai. Change requested, nes labai atsilieka nuo develop brancho sitas pr

2021-01-13 10:01 UTC, sunshinepro commented on css/components/logo-banner.css
> +    margin-right: 30px;
Rodo, kad prašai pakeitimų
![image](https://user-images.githubusercontent.com/74533174/104437129-54b41a00-5586-11eb-89e4-4839dcbc19c6.png)

2021-01-13 11:32 UTC, Lukasring approved these changes

2021-03-01 11:47 UTC, merged